apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-gitops-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/mnt/data"
